### ISSUE TITLE
mismatch of flatten() calls in rp_extract

### ISSUE THREAD

**Issue by audiofeature** [tuwien-musicir/rp_extract#16]
Throughout rp_extract.py an numerous positions in the code the various types of extracted features are flattened to a vectore instead of a matrix, using numpy.ndarray.flatten().

Flatten has an optional parameter `order`, to set "whether to flatten in row-major (C-style) or column-major (Fortran-style) order or preserve the C/Fortran ordering from a. The default is ‘C’."
( http://docs.scipy.org/doc/numpy-1.10.1/reference/generated/numpy.ndarray.flatten.html )

The intention here was originally to use the Matlab order for compatibility to the prior Matlab code, which would be the "F" option (Matlab = Fortran ordering).

However, there seems to be not only a mismatch of various options across the positions, but also frequently the parameter 1 is passed, which is not defined, but seems to match with the 'F' option.

`
ssd_list.append(ssd.flatten(1))
rp_list.append(rp.flatten(order='F')) 
features["sh"] = np.asarray(sh).flatten('C')
features["tssd"] = calc_statistical_features(np.asarray(ssd_list).transpose()).flatten(1)
`

A particular problem with the 'F' (or 1) order is that the dimensions are garbled when reshape is used afterwards, forgetting to use the same order (which is difficult, given the different orderings when flattening).

=> The flatten ordering should be carefully aligned between **all** feature types and results. 

**Be aware that this results in making any features stored previously as CSV or NPZ  _incompatible_ to the result after this change!**

**Comment by slychief** [comment]
the spectral histograms were a not successful experiment and I was surprised to still see them in the code. The mentioned mismatch in ordering did not influence the other features and refers to that specific experiment. For all other transformations I am convinced that the ordering is consistent, because I double checked the resulting values with the Matlab implementation.

**Comment by audiofeature** [comment]
removed sh features in  c15ecc7
