### ISSUE TITLE
wavio changed the api

### ISSUE THREAD

**Issue by slychief** [tuwien-musicir/rp_extract#18]
0.0.4.dev0 changed the interface leading to the following error:

> AttributeError: 'module' object has no attribute 'readwav'

new method:

```

w = wavio.read(filename)
self.assertEqual(w.rate, 44100)
self.assertEqual(w.sampwidth, 1)
self.assertEqual(w.data.dtype, np.uint8)
self.assertEqual(w.data.shape, (32, 1))
```

**Comment by audiofeature** [comment]
why are we affected by this? we include the (original) source file of 
wavio in the rp_extract rep

Am 21.03.2016 um 14:50 schrieb Alexander Schindler:

> 0.0.4.dev0 changed the interface leading to the following error:
> 
> ```
> AttributeError: 'module' object has no attribute 'readwav'
> ```
> 
> new method:
> 
> |w = wavio.read(filename) self.assertEqual(w.rate, 44100) 
> self.assertEqual(w.sampwidth, 1) self.assertEqual(w.data.dtype, 
> np.uint8) self.assertEqual(w.data.shape, (32, 1)) |
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub 
> https://github.com/tuwien-musicir/rp_extract/issues/18

## 

Thomas Lidy
Vienna University of Technology
Institute of Software Technology and Interactive Systems
Favoritenstraße 9-11/188
A-1040 Vienna

http://www.ifs.tuwien.ac.at/~lidy
http://musicbricks.net/

**Comment by slychief** [comment]
OK
